server:
  port: 0

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    shard0:
      url: jdbc:mariadb://localhost:3306/gameinfo_order
    shard1:
      url: jdbc:mariadb://localhost:3306/gameinfo_order2
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 5000
  application:
    name: order-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    config:
      name: gameinfo
    openfeign:
      circuitbreaker:
        enabled: true
  config:
    import:
      - "optional:configserver:http://localhost:9088"
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        use_id_generator_strategy_three_lo: false
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - busrefresh
          - prometheus
          - metrics