spring:
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate

services:
  user-service:
    url: http://localhost:${wiremock.server.port}
  catalog-service:
    url: http://localhost:${wiremock.server.port}
  key-inventory-service:
    url: http://localhost:${wiremock.server.port}